version: "3"

volumes: 
  mysql-data:

services:
  nginx:
    image: nginx:stable-alpine
    network_mode: host
    ports: 
      - 80:80
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./pub:/home/n9e/pub

  nightingale:
    build: .
    image: nightingale

  monapi:
    image: nightingale
    network_mode: host
    restart: always
    command: n9e-monapi
    ports: 
      - 5800:5800
      
  transfer:
    image: nightingale
    network_mode: host
    restart: always
    command: n9e-transfer
    ports: 
      - 5810:5810
      - 5811:5811

  tsdb:
    image: nightingale
    network_mode: host
    restart: always
    command: n9e-tsdb
    ports: 
      - 5820:5820
      - 5821:5821
      
  index:
    image: nightingale
    network_mode: host
    restart: always
    command: n9e-index
    ports: 
      - 5830:5830
      - 5831:5831

  judge:
    image: nightingale
    network_mode: host
    restart: always
    command: n9e-judge
    ports: 
      - 5840:5840
      - 5841:5841

  collector:
    image: nightingale
    network_mode: host
    restart: always
    command: n9e-collector
    ports: 
      - 2058:2058

  redis:
    image: redis
    network_mode: host
    restart: always
    ports: 
      - 6379:6379

  mysql:
    image: mysql:5.7
    network_mode: host
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports: 
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
