// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  router

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( HTTPMetric ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* HTTPMetric ) UnmarshalJSON([]byte) error { return nil }
func ( HTTPMetric ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* HTTPMetric ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_HTTPMetric *HTTPMetric

func ( HTTPMetricArr ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* HTTPMetricArr ) UnmarshalJSON([]byte) error { return nil }
func ( HTTPMetricArr ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* HTTPMetricArr ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_HTTPMetricArr *HTTPMetricArr
