# As of 3.8.0, RabbitMQ ships with built-in Prometheus & Grafana support.
# Support for Prometheus metric collector ships in the rabbitmq_prometheus plugin.
# The plugin exposes all RabbitMQ metrics on a dedicated TCP port, in Prometheus text format.
#
# enable prometheus plugin:
# `rabbitmq-plugins enable rabbitmq_prometheus`
# `curl http://localhost:15692/metrics`
# 
# then use categraf prometheus plugin scrape http://localhost:15692/metrics instead of this rabbitmq plugin

# # collect interval
# interval = 15

[[instances]]
# # Management Plugin url
# url = "http://localhost:15672"
# username = "guest"
# password = "guest"

## Optional TLS Config
# use_tls = false
# tls_min_version = "1.2"
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
# insecure_skip_verify = true

## Optional request timeouts
##
## ResponseHeaderTimeout, if non-zero, specifies the amount of time to wait
## for a server's response headers after fully writing the request.
# header_timeout = "3s"
##
## client_timeout specifies a time limit for requests made by this client.
## Includes connection time, any redirects, and reading the response body.
# client_timeout = "4s"

## A list of nodes to gather as the rabbitmq_node measurement. If not
## specified, metrics for all nodes are gathered.
# nodes = ["rabbit@node1", "rabbit@node2"]

## A list of exchanges to gather as the rabbitmq_exchange measurement. If not
## specified, metrics for all exchanges are gathered.
# exchanges = ["categraf"]

## Metrics to include and exclude. Globs accepted.
## Note that an empty array for both will include all metrics
## Currently the following metrics are supported: "exchange", "federation", "node", "overview", "queue"
# metric_include = []
# metric_exclude = []

## Queues to include and exclude. Globs accepted.
## Note that an empty array for both will include all queues
# queue_name_include = []
# queue_name_exclude = []

## Federation upstreams to include and exclude specified as an array of glob
## pattern strings.  Federation links can also be limited by the queue and
## exchange filters.
# federation_upstream_include = []
# federation_upstream_exclude = []

# # interval = global.interval * interval_times
# interval_times = 1

# important! use global unique string to specify instance
# labels = { instance="rabbitmq-001" }