name: Bug Report
description: Report a bug encountered while running Nightingale
labels: ["kind/bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking time to fill out this bug report! 
        The more detailed the form is filled in, the easier the problem will be solved.
  - type: textarea
    id: config
    attributes:
      label: Your config.toml
      description: Place config in the toml code section. This will be automatically formatted into toml, so no need for backticks.
      render: toml
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: categraf | telegraf | n9e | prometheus | chrome request/response ...
      render: text
    validations:
      required: true
  - type: input
    id: system-info
    attributes:
      label: System info
      description: Include nightingale version, operating system, and other relevant details
      placeholder: ex. n9e 5.9.2, n9e-fe 5.5.0, categraf 0.1.0, Ubuntu 20.04, Docker 20.10.8
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen when you performed the above steps.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happened when you performed the above steps.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Include gist of relevant config, logs, etc.
    validations:
      required: false
