name: Bug Report & Usage Question
description: Reporting a bug or asking a question about how to use Nightingale 
labels: []

body:
  - type: markdown
    attributes:
      value: |
        The more detailed the form is filled in, the easier the problem will be solved.
        Before asking, please search existing issues (including closed ones) to avoid duplicates.
  - type: textarea
    id: question
    attributes:
      label: Question and Steps to reproduce
      description: Describe your question and steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs and configurations
      description: Relevant error logs and the configurations of the related components. See the [docs](https://n9e.github.io/) for how to check logs.
      render: text
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Version
      description: Include nightingale version, operating system version, CPU architecture, and other relevant details.
    validations:
      required: true
 
