FROM flashcatcloud/toolbox:v0.0.1 as toolbox
FROM --platform=$TARGETPLATFORM python:3-slim


WORKDIR /app
ADD n9e /app/
ADD etc /app/
ADD integrations /app/integrations/
COPY --chmod=755  --from=toolbox /toolbox/wait_aarch64 /wait

EXPOSE 17000

CMD ["/app/n9e", "-h"]
