FROM --platform=$TARGETPLATFORM python:3-slim


WORKDIR /app
ADD n9e /app/
ADD etc /app/
ADD integrations /app/integrations/
ADD --chmod=755 https://github.com/ufoscout/docker-compose-wait/releases/download/2.11.0/wait_x86_64 /wait
RUN chmod +x /wait

EXPOSE 17000

CMD ["/app/n9e", "-h"]
