FROM --platform=$BUILDPLATFORM python:2.7.8-slim


WORKDIR /app
ADD n9e /app
ADD etc /app
ADD http://download.flashcat.cloud/wait /wait
RUN mkdir -p /app/pub && chmod +x /wait
ADD pub /app/pub/
RUN chmod +x n9e

EXPOSE 17000

CMD ["/app/n9e", "-h"]
