# # collect interval
# interval = 15

disable_summary_stats = false
## if machine has many network connections, use this plugin may exhaust your cpu resource, diable connection stat to avoid this
disable_connection_stats = true

tcp_ext = false
ip_ext = false
