version: '3.6'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: nginx 
    container_name: nginx-n9e
    hostname: nginx-n9e
    ports:
      - 80:80
    restart: unless-stopped
    links:
      - n9e:n9e

  mysql:
    image: mysql:5
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    # volumes: 
      # - /usr/local/docker/mysql/data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

  n9e:
    build:
      dockerfile: Dockerfile
      context: n9e
    container_name: n9e
    hostname: n9e
    ports:
      - 8000:8000
      - 8002:8002
      - 8004:8004
      - 8005:8005
      - 8006:8006
      - 8008:8008
      - 8009:8009
      - 8010:8010
      - 8011:8011
      - 8012:8012
      - 8013:8013
      - 8014:8014
      - 8015:8015
      - 2080:2080
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
