[[instances]]
  urls = ["http://localhost:8080/jolokia"]
  name_prefix = "zk_"

  [[instances.metric]]
    name  = "quorum"
    mbean = "org.apache.ZooKeeperService:name0=*"
    tag_keys = ["name0"]

  [[instances.metric]]
    name = "leader"
    mbean = "org.apache.ZooKeeperService:name0=*,name1=*,name2=Leader"
    tag_keys = ["name1"]

  [[instances.metric]]
    name = "follower"
    mbean = "org.apache.ZooKeeperService:name0=*,name1=*,name2=Follower"
    tag_keys = ["name1"]
