# # collect interval
# interval = 15

[[instances]]
# # append some labels for series
# labels = { region="cloud", product="n9e" }

# # interval = global.interval * interval_times
# interval_times = 1

## Server to monitor
## The scheme determines the mode to use for connection with
##    ldap://...      -- unencrypted (non-TLS) connection
##    ldaps://...     -- TLS connection
##    starttls://...  --  StartTLS connection
## If no port is given, the default ports, 389 for ldap and starttls and
## 636 for ldaps, are used.
#server = "ldap://localhost"

## Server dialect, can be "openldap" or "389ds"
# dialect = "openldap"

# DN and password to bind with
## If bind_dn is empty an anonymous bind is performed.
bind_dn = ""
bind_password = ""

## Reverse the field names constructed from the monitoring DN
# reverse_field_names = false

## Optional TLS Config
# use_tls = false
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
# insecure_skip_verify = false